[program:messenger-consume]
command=php /application/bin/console messenger:consume high_priority_async async --limit=10
user=www-data
numprocs=5
startsecs=0
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d